const API_PORT_DEFAULT = 7292;
const API_CALL_URL_DEFAULT = null;
const WALLET_UNLOCK_TIME_DEFAULT = 15;
const NFT_TIMEOUT_DEFAULT = 15;
const PASSWORD_CLEAR_TIME_DEFAULT = 10;
const AUTO_DOWNLOAD_NFT_ASSET_DEFAULT = true;
const IGNORE_INCOMING_NFTS_DEFAULT = false;
const REJECT_ASSET_EXTENSION_TYPES_DEFAULT = null;
const ALLOWED_EXTENSION_TYPES_DEFAULT = null;

const NON_CONFIGURABLE_SETTINGS = [
  'MotherAddress',
  'MotherPassword',
];
